### ISSUE TITLE
Cmix client_id/client_secret

### ISSUE THREAD

**Issue by RazvanCretu** [dynata/python-cmixapi-client#111]
Hi 
@wogsland @dynata-bradley 

I am Data Processor for Dynata.

I've recently seen this module which looks very interesting to me and I wish explore it so I could automate some of the DP work.

Could you please let me know where I could find these client_id/secret? I do have rights to download data from the cmix platform as a DP. But wasn't able to find client_id nor client_secret.

Thanks in advance!

**Comment by wogsland** [comment]
Sorry, I'm no longer with Dynata so I don't know who's maintaining this repository.

**Comment by DynataRidley** [comment]
Hi @RazvanCretu, please contact the IT help desk for credentials to the CMIX API.
